services:
    sculpin_content_types.types.articles.collection.sorter:
        class: Sculpin\Contrib\ProxySourceCollection\Sorter\MetaSorter
        arguments:
             - title
    sculpin_taxonomies.taxonomies.categories.collection.sorter:
        class: Sculpin\Contrib\ProxySourceCollection\Sorter\MetaSorter
        arguments:
             - title
    sculpin_content_types.types.guides.collection.sorter:
        class: Sculpin\Contrib\ProxySourceCollection\Sorter\MetaSorter
        arguments:
             - title
    twig.extension.text:
            class: Twig_Extensions_Extension_Text
            tags:
                - { name: twig.extension }
